shader_type canvas_item;

uniform vec3 color_override: source_color;

void vertex() {
	// Called for every vertex the material is visible on.
}

void fragment() {
	//if (COLOR.r > 0.1){
		COLOR = vec4(color_override.r, color_override.g, color_override.b, COLOR.a);
	//}
}

//void light() {
	// Called for every pixel for every light affecting the CanvasItem.
	// Uncomment to replace the default light processing function with this one.
//}
